name: Publish release to Pypi

on:
  push:
    # run only against tags
    tags:
      - '*'
      
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0 # needed to retrieve most recent tag
    - name: Set up Python '3.11'
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Build
      run: make build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}